version: '3.4'

services:
  coravel-demo-consoleapp:
    image: ${DOCKER_REGISTRY-}coraveldemoconsoleapp
    build:
      context: .
      dockerfile: Coravel-Demo-ConsoleApp/Dockerfile
    networks:
      - app-net

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - app-net


networks:
  app-net:
    driver: bridge